#region Using directives

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

#endregion

[assembly: AssemblyTitle("Adiict.TabControlExtraDemo")]
[assembly: AssemblyDescription("Displays various tab styles generated by the Adiict.TabControlExtra component.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Adiict")]
[assembly: AssemblyProduct("Adiict.TabControlExtraDemo")]
[assembly: AssemblyCopyright("Copyright © Mark Jackson 2010; Richard L King 2012-2018; Adiict 2026")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: NeutralResourcesLanguage("en-GB")]
[assembly: CLSCompliant(true)]

[assembly: ComVisible(false)]

[assembly: AssemblyVersion("3.0.0")]
